# Generated by Django 5.1.2 on 2024-10-27 22:16

import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_name",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="profile name"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="thumbnail",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to="static/users/users_thumbnails/",
                verbose_name="thumbnail",
            ),
        ),
    ]
