# Generated by Django 5.1.2 on 2024-11-07 16:39

import core.utils.field
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_entry_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="uid",
            field=core.utils.field.UidField(default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="uid",
            field=core.utils.field.UidField(default=uuid.uuid4, null=True),
        ),
    ]
