# Generated by Django 5.1.2 on 2024-11-07 16:40

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    topic_model = apps.get_model("core", "Topic")
    for row in topic_model.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=["uid"])
    entry_model = apps.get_model("core", "Entry")
    for row in entry_model.objects.all():
        row.uid = uuid.uuid4()
        row.save(update_fields=["uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_entry_uid_topic_uid"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
