# Generated by Django 5.1.2 on 2024-11-07 16:40

import core.utils.field
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_uuid_field_filling"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="uid",
            field=core.utils.field.UidField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="uid",
            field=core.utils.field.UidField(
                db_index=True, default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
